### ISSUE TITLE
Lion issues

### ISSUE THREAD

**Issue by thightower** [chetan51/sidestep#27]
Seems to be issues with Lion at least in my case no connection to remote host. Actually connection is established but when checking IP it gives my WAN and not that of my server which is hosted off site. I have only been able to check this on one Mac, hopefully in a few days more or so a few more people can check this out.

**Comment by chetan51** [comment]
Sidestep does not route all of your traffic through the tunnel, only the applications that support the system-wide SOCKS proxy. Please try checking your IP in Safari and let me know if it is working or not.

**Comment by thightower** [comment]
Uh yep,.... in Safari it reports my WAN and not that of my server, I am familiar in how it works tho as it works flawlessly in my SL partition, and on other Macs running SL. If I want a use a true vpn then I use tunnelblick to my server. OpenVPN on Ubuntu.
I have another iMac in the office running Lion, which I just installed SS on and it exhibited the same behavior, and just like my MBP tunnelblick is working fine. (note iMac is connected wireless only to LAN)

IP checked in Safari via tunnelblick show, server IP
IP checked in Safari via SideStep show my iMacs WAN IP (note tunnelblick disconnected for this test =) )

One quandary I had to force a connection as my connection is secured, I may take the MacBook to a free wifi and just see how it works on an unsecured connection which I didn't have to manually set via the SS pref.

**Comment by chetan51** [comment]
Looks like Sidestep is not able to modify the system-wide SOCKS proxy
setting in Lion. I'll look into it soon.

**Comment by chetan51** [comment]
Update: I've just released an update that makes Sidestep work on Lion. Everything should be fine now.

**Comment by ironworld** [comment]
Hi chetan51!

I'm running Sidestep version 1.3.1 and I'm having the same problem. The Lion version is Mac OS X Lion 10.7.3 (11D50).

Thanks.
