### ISSUE TITLE
Feature Req: HTTP and HTTPS proxy support

### ISSUE THREAD

**Issue by nutinshell** [chetan51/sidestep#28]
Sidestep is easy and cool, but it only support socks proxy...

I like to use 

ssh -L lport:host:rport user@host -N 

to create HTTP proxy other than socks proxy, if Sidestep add HTTP(HTTPS) proxy support, that would be more cool!

**Comment by axtl** [comment]
This doesn't make sense, because a SOCKS proxy will route [all TCP connections](https://en.wikipedia.org/wiki/SOCKS5#Comparison); it's at a lower level than HTTP(S), so you can already use it for the described purpose.
