### ISSUE TITLE
No connection after reroute

### ISSUE THREAD

**Issue by b1tchnow** [chetan51/sidestep#33]
Hi,

I installed Sidestep and configured it to use SSH on my webhosting server. The connection test in the preferences runs successfully.
If I reroute the traffic manually, I can't get any connection afterwards. If I set it back to normal routing without SSH it works as usual.

What am I missing and how can I find a point to fix it?

Regards,
b1tchnow

**Comment by chetan51** [comment]
What are you using to test your Internet connection?

**Comment by b1tchnow** [comment]
A secured WLAN and Chrome or what do you need to know?

**Comment by b1tchnow** [comment]
I fixed the issue. I had to activate the Option "Auto Proxy Discovery" in the advanced network settings in the "Proxies" settings.

Can you confirm this as a valid solution, chetan51?

**Comment by chetan51** [comment]
Really? Mine was never activated, but it still worked. Not sure why that fixed it for you. But it's great that you figured it out!

**Comment by b1tchnow** [comment]
I can't help it, but it worked.

I also recognized, the only thing I could not do, was browsing the WWW with a browser. Other applications like Audium kept their connection after I rerouted the traffic. Only the browser could not connect to the server without setting the option mentioned above.

Maybe this helps others. :-)
