### ISSUE TITLE
HowTo setup Transmit?

### ISSUE THREAD

**Issue by jchatard** [chetan51/sidestep#34]
Hi,

I'm using SideStep to re-route all (the possible) traffic through my server (using SSH), and was trying to get Transmit using my server too.

I'm really not a Proxy / Socks guru at all. Under Transmit there are a lot of proxy options like SOCKS 4, SOCKS 4a, SOCKS 5...

I tried severals but didn't get my FTP connections to work.

Any feedback on this?

Thanks,
Jérémy

**Comment by chetan51** [comment]
Hmm, I'm not sure actually. It depends on how Transmit handles SOCKS proxies. Ideally, it should just use the system-wide SOCKS proxy that you can set in Advanced Network system preferences.

**Comment by jchatard** [comment]
Ok thanks,

I've just sent an email to Panic support. If they have any documentation, advice, etc.

If I got it working I'll update this issue.

**Comment by jchatard** [comment]
Ok I finally succeed with the following.

In Transmit proxy settings:
- Proxy type: `SOCKS 5`
- Proxy host: `127.0.0.1`
- Proxy port: `9050`

Which is what is set by Sidestep - _I think_ - in the general network settings, when re-routing traffic.

Thanks,
Jérémy

**Comment by chetan51** [comment]
Ah, that makes sense. Thanks for updating this comment!
