### ISSUE TITLE
Can't restore direct connection

### ISSUE THREAD

**Issue by originell** [chetan51/sidestep#39]
Since one of the 10.7.X updates the "restore direct connection" menu item doesn't work anymore. As a workaround I'm always disabling the SOCKS proxy in the net settings and killing the ssh tunnel afterwards.. Reopening sidestep after that.

If you need any more information tell me. Right now I'm running 10.7.4 with newest XCode (if that matters). Haven't compiled Sidestep myself.

**Comment by chetan51** [comment]
Is the button disabled, or it just has no effect when you click on it? What exactly happens when you click on it (including notifications and such)?

**Comment by originell** [comment]
It has no effect when I click on it. Well I don't have growl installed, but if it helps I'll install it?

My scenario:

#. I'm in an encrypted (trusted) wifi
#. I let Sidestep reroute (need my other IP for some ssh stuff etc.)
#. Doing my stuff
#. Want to restore direct connection. Clicking on the button but nothing happens.

**Comment by chetan51** [comment]
Instead of pressing the button to disable the rerouting, try running the following two commands in Terminal and copy-paste the output here (also check if it properly disabled the rerouting or not):

```
networksetup -setsocksfirewallproxystate Airport off
networksetup -setsocksfirewallproxystate Wi-Fi off
```

**Comment by originell** [comment]
I've restarted my macbook a couple days ago and since then it works flawlessly. Hopefully I can reproduce the state before somehow ;-)

**Comment by originell** [comment]
So I finally got it buggy again:

```
% networksetup -setsocksfirewallproxystate Airport off
** Error: Unable to find item in network database.
```

but the other command worked flawlessly:

```
% networksetup -setsocksfirewallproxystate Wi-Fi off
```

and it disabled the proxy in the preferences.

**Comment by chetan51** [comment]
Yeah, only one of them is supposed to work, depending on whether you're on Leopard or Lion.

**Comment by originell** [comment]
Ah okay. Well then I guess I might just run a sidestep version with some logging to a file. Or is "Xlog" already doing this? I'M not much of a objc guy ;)
