### ISSUE TITLE
Always prompted for permission to access system.preferences

### ISSUE THREAD

**Issue by gerdemb** [chetan51/sidestep#50]
Every time Sidestep is launched, it asks for the user's password for access to 'system.preferences'. There should be a way to remember this password so that the user is not always prompted.

Sidestep: 1.3.2
OS X: 10.6.8

**Comment by chetan51** [comment]
Is it only on launch? If so, that's a security measure imposed by the operating system, and there's nothing we can (or should) do about it.

**Comment by gerdemb** [comment]
Is there really nothing that can be done about this? I understand prompting for the password once, but usually there's a choice for "always allow" or something to that effect. It works in Lion without prompting for the password on every launch.

**Comment by dgomes** [comment]
Every time you launch sidestep it request you authorization to change your settings. The authorization is cached for the duration of the application (until you quit Sidestep).

The "always allow" is related to a different authorization API than the one required by sidestep unfortunately...
