### ISSUE TITLE
How to use private key with Sidestep?

### ISSUE THREAD

**Issue by bcamp1973** [chetan51/sidestep#64]
I'm using the following command, but not luck...

`-i ~/.ssh/personalKey`

**Comment by zacs** [comment]
When you SSH into the host from Terminal, what command do you use? `ssh hostname.foo -i ~/.ssh/personalKey`?

**Comment by bcamp1973** [comment]
Forgot I posted here :) Thanks for replying, but it seems to be working now with the command i posted above. It seems there were some firewall issues that were confusing matters
